secret_key = ""

google_client_id = ""
google_client_secret = ""

aws_access_key_id = ""
aws_secret_access_key = ""
aws_endpoint_url = ""

smtp_user = ""
smtp_password = ""

coingecko_api_key = ""


development_mode = true
project_name = "Auth API"
api_v1_str = "/api/v1"

algorithm = "HS256"
access_token_expire_minutes = 30

google_redirect_uri = "http://localhost:8000/api/v1/auth/google/callback"

aws_region = "us-east-1"
dynamodb_users_table = "users"
dynamodb_otp_table = "otp_codes"

otp_expire_minutes = 10

smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_tls = true

coingecko_pro_enabled = false
use_localstack = false